"""EnvManager — orchestrator for ``shimkit env``.

Read-only by design: ``show`` / ``list`` / ``diff`` never mutate.
The single mutator (``scaffold``) writes a fresh file from a template
and refuses to overwrite an existing one. Reuses the secret-key
redactor from :mod:`shimkit.tools.env.parser`.
"""

from __future__ import annotations

import sys
from pathlib import Path

from shimkit.config import get_config
from shimkit.core import UI, Event, Menu, Platform, emit_json, get_logger

from . import parser as _parser

_LOG = get_logger("env")

EX_OK = 0
EX_FAIL = 1
EX_UNAVAILABLE = 69

_TEMPLATE = """# {name}
# Generated by `shimkit env scaffold`. Replace placeholders before use.

# Application
APP_NAME=myapp
APP_ENV=development
LOG_LEVEL=info

# Secrets — fill in. shimkit env will redact these by default.
API_KEY=
DATABASE_PASSWORD=
"""


class EnvManager:
    def __init__(self) -> None:
        self._platform: Platform | None = None

    @classmethod
    def create(cls) -> EnvManager:
        return cls()

    def boot(self) -> EnvManager:
        self._platform = Platform.detect()
        # `.env` is just text — no OS gate needed beyond the
        # unix/macos charter check.
        if not (self._platform.is_macos or self._platform.is_linux):
            UI.error(
                f"shimkit env targets macOS and Linux. Detected platform: {self._platform.system}."
            )
            sys.exit(EX_UNAVAILABLE)
        return self

    # ─── show ──────────────────────────────────────────────────────────

    def show(
        self,
        path: Path | None,
        *,
        reveal: bool = False,
        json_out: bool = False,
    ) -> int:
        target = path or self._resolve_default()
        if target is None:
            UI.error("No .env file found in cwd. Pass an explicit PATH.")
            return EX_FAIL
        if not target.is_file():
            UI.error(f"Not a file: {target}")
            return EX_FAIL
        env = _parser.parse(target.read_text(encoding="utf-8", errors="replace"))
        cfg = get_config().tools.env
        if json_out:
            emit_json(
                Event(
                    tool="env",
                    step="show",
                    status="ok",
                    data={
                        "path": str(target),
                        "reveal": reveal,
                        "entries": [
                            {
                                "key": e.key,
                                "value": (
                                    e.value
                                    if reveal
                                    or not _parser.is_secret_key(e.key, cfg.redact_pattern)
                                    else _parser.redact_value(e.value)
                                ),
                                "redacted": (
                                    not reveal
                                    and _parser.is_secret_key(e.key, cfg.redact_pattern)
                                    and bool(e.value)
                                ),
                                "comment": e.comment,
                            }
                            for e in env.entries()
                        ],
                    },
                )
            )
            return EX_OK
        UI.header(f".env — {target}" + ("  (--reveal)" if reveal else "  (secrets redacted)"))
        rendered = _parser.render_redacted(env, pattern=cfg.redact_pattern, reveal=reveal)
        UI.line(rendered)
        return EX_OK

    # ─── list ──────────────────────────────────────────────────────────

    def list_files(self, root: Path, *, json_out: bool = False) -> int:
        """Walk ``root`` and report every .env* file found.

        Method name is ``list_files`` (not ``list``) so it doesn't shadow
        the builtin in callers' type annotations.
        """
        candidates: list[Path] = sorted(self._walk_envs(root))
        if json_out:
            emit_json(
                Event(
                    tool="env",
                    step="list",
                    status="ok",
                    data={
                        "root": str(root),
                        "files": [str(p) for p in candidates],
                    },
                )
            )
            return EX_OK
        if not candidates:
            UI.info(f"No .env* files under {root}.")
            return EX_OK
        UI.header(f"{len(candidates)} .env* file(s) under {root}")
        for p in candidates:
            UI.line(f"  {p.relative_to(root)}")
        return EX_OK

    # ─── scaffold ──────────────────────────────────────────────────────

    def scaffold(self, target: Path, *, dry_run: bool = False) -> int:
        if target.exists():
            UI.error(f"{target} already exists; refusing to overwrite.")
            return EX_FAIL
        body = _TEMPLATE.format(name=target.name)
        if dry_run:
            UI.info(f"--dry-run: would write {len(body)} bytes to {target}.")
            return EX_OK
        try:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(body, encoding="utf-8")
        except OSError as exc:
            UI.error(f"Could not write {target}: {exc}")
            return EX_FAIL
        UI.success(f"Wrote scaffold to {target}.")
        return EX_OK

    # ─── diff ──────────────────────────────────────────────────────────

    def diff(self, a: Path, b: Path, *, json_out: bool = False) -> int:
        for p in (a, b):
            if not p.is_file():
                UI.error(f"Not a file: {p}")
                return EX_FAIL
        ea = _parser.parse(a.read_text(encoding="utf-8", errors="replace"))
        eb = _parser.parse(b.read_text(encoding="utf-8", errors="replace"))
        d = _parser.diff_keys(ea, eb)
        if json_out:
            emit_json(
                Event(
                    tool="env",
                    step="diff",
                    status="ok",
                    data={"a": str(a), "b": str(b), **d},
                )
            )
            return EX_OK
        UI.header(f"diff: {a}  ↔  {b}")
        if d["only_a"]:
            UI.line(f"  only in {a.name}: {', '.join(d['only_a'])}")
        if d["only_b"]:
            UI.line(f"  only in {b.name}: {', '.join(d['only_b'])}")
        if d["differ"]:
            UI.line(f"  values differ: {', '.join(d['differ'])}")
        if not any(d.values()):
            UI.success("Both files have the same key set and values.")
        return EX_OK

    # ─── redact (write a redacted copy) ────────────────────────────────

    def redact(self, src: Path, dst: Path, *, dry_run: bool = False) -> int:
        if not src.is_file():
            UI.error(f"Not a file: {src}")
            return EX_FAIL
        if dst.exists():
            UI.error(f"{dst} already exists; refusing to overwrite.")
            return EX_FAIL
        env = _parser.parse(src.read_text(encoding="utf-8", errors="replace"))
        cfg = get_config().tools.env
        body = _parser.render_redacted(env, pattern=cfg.redact_pattern, reveal=False)
        if dry_run:
            UI.info(f"--dry-run: would write {len(body)} bytes to {dst}.")
            return EX_OK
        try:
            dst.parent.mkdir(parents=True, exist_ok=True)
            dst.write_text(body, encoding="utf-8")
        except OSError as exc:
            UI.error(f"Could not write {dst}: {exc}")
            return EX_FAIL
        UI.success(f"Wrote redacted copy of {src} to {dst}.")
        return EX_OK

    # ─── interactive ──────────────────────────────────────────────────

    def run(self) -> None:
        while True:
            picked = Menu.select(
                "shimkit env",
                [
                    "Show current .env (redacted)",
                    "List .env* files under cwd",
                    "Quit",
                ],
            )
            if picked is None or picked == "Quit":
                return
            if picked == "Show current .env (redacted)":
                self.show(None)
            elif picked == "List .env* files under cwd":
                self.list_files(Path.cwd())

    # ─── internal ──────────────────────────────────────────────────────

    def _resolve_default(self) -> Path | None:
        cfg = get_config().tools.env
        cwd = Path.cwd()
        for name in cfg.default_search_paths:
            candidate = cwd / name
            if candidate.is_file():
                return candidate
        return None

    def _walk_envs(self, root: Path) -> list[Path]:
        """Find every ``.env*`` regular file under ``root``.

        Skip hidden directories like ``.git`` so we don't trip on
        committed `.env.example` files inside vendor dirs.
        """
        out: list[Path] = []
        if not root.is_dir():
            return out
        for dirpath, dirnames, filenames in _walk(root):
            # Prune hidden + node_modules / vendor dirs.
            dirnames[:] = [
                d for d in dirnames if not d.startswith(".") and d not in {"node_modules", "vendor"}
            ]
            for fn in filenames:
                if fn == ".env" or fn.startswith(".env."):
                    out.append(dirpath / fn)
        return out


def _walk(root: Path):  # type: ignore[no-untyped-def]
    """``os.walk`` wrapper yielding ``Path`` objects.

    Indirection keeps the manager free of ``os.walk`` import noise
    and makes the walker swappable in tests.
    """
    import os

    for dirpath, dirnames, filenames in os.walk(root):
        yield Path(dirpath), dirnames, filenames
